services:
  - type: web
    name: flask-lab1-variant7
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
